name: entiendo
description: Entiendo es una plataforma que nos permite aprender y organizarnos a la distancia.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.1.3
  date_picker_timeline: ^1.2.0
  expansion_tile_card: ^1.0.3
  pull_to_refresh: ^1.5.8
  http: ^0.12.1

  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
      - assets/images/

  fonts:
   - family: HKGrotesk-Regular
     fonts:
       - asset: assets/fonts/HKGrotesk-Regular.otf

   - family: HKGrotesk-Light
     fonts:
       - asset: assets/fonts/HKGrotesk-Light.otf

   - family: HKGrotesk-Medium
     fonts:
       - asset: assets/fonts/HKGrotesk-Medium.otf

   - family: HKGrotesk-Bold
     fonts:
       - asset: assets/fonts/HKGrotesk-Bold.otf